---
title: "EconomicNihilism_Pt1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(devtools)
library(tidyverse)
library(lubridate)
library(readr)
library(janitor)
library(here)
library(haven)
library(tigris)
library(tidycensus)
library(purrr)
library(ipumsr)
library(data.table)
library(stringr)
library(httr2)
library(jsonlite)
library(dplyr)
library(slider)
```

```{r Step 1: CES Data Ingestion, include=TRUE}
ces25 <- read_dta(here("00_rawdata", "CES25_Common.dta"))
ces24 <- read_dta(here("00_rawdata", "CCES24_Common_OUTPUT_vv_topost_final.dta"))
ces23 <- read_dta(here("00_rawdata", "CCES23_Common_OUTPUT.dta"))
ces22 <- read_dta(here("00_rawdata", "CCES22_Common_OUTPUT_vv_topost.dta"))
ces21 <- read_dta(here("00_rawdata", "CCES21_Common_OUTPUT.dta"))
ces20 <- read_dta(here("00_rawdata", "CES20_Common_OUTPUT_vv.dta"))
ces19 <- read_dta(here("00_rawdata", "CCES19_Common_OUTPUT.dta"))
ces18 <- read_dta(here("00_rawdata", "cces18_common_vv.dta"))
ces17 <- read_dta(here("00_rawdata", "CES_Common_2017.dta"))
ces17_county_addition <- read_csv(here("00_rawdata", "CCES17_Common_county.csv"))
ces16 <- read_dta(here("00_rawdata", "CCES16_Common_OUTPUT_Feb2018_VV.dta"))
ces15 <- read_dta(here("00_rawdata", "CCES15_Common_OUTPUT_Jan2016.dta"))
ces14 <- read_dta(here("00_rawdata", "CCES14_Common_Content_Validated.dta"))
ces13 <- read_dta(here("00_rawdata", "ces13.dta"))
ces12 <- read_dta(here("00_rawdata", "CCES12_Common_VV.dta"))
ces11 <- read_dta(here("00_rawdata", "CCES11_Common_OUTPUT.dta"))
ces10 <- read_dta(here("00_rawdata", "cces_2010_common_validated.dta"))
ces09 <- read_dta(here("00_rawdata", "cces09_cmn_output_2.dta"), encoding = "latin1")
ces08 <- read_dta(here("00_rawdata", "cces_2008_common.dta"))
ces07 <- read_sav(here("00_rawdata", "CCES07_OUTPUT.sav"), encoding = "latin1")
ces06 <- read_dta(here("00_rawdata", "cces_2006_common.dta"))

qwi_panel <- read_csv(here("01_tidydata", "QuarterlyWorkforceIndicators0625.csv"))

county_ideology_1 <- read_dta(here("00_rawdata", "aip_counties_ideology_v2022a.dta"))
county_presvote_1 <- read_dta(here("00_rawdata", "aip_counties_sub_ideology_v2022a.dta"))
county_presvote_2 <- read_dta(here("00_rawdata", "aip_counties_pvote.dta"))
```

```{r Step 2: Census QWI Pull, include=TRUE}
my_key <- Sys.getenv("census_api_key")

#Function to pull a single state-quarter combination
get_qwi_county <- function(state_fips,
                           time_period,
                           variable) {
  
  req <- request("https://api.census.gov/data/timeseries/qwi/sa") |>
    req_url_query(
      get = variable,
      `for` = "county:*",
      `in` = paste0("state:", state_fips),
      time = time_period,
      sex = "0",
      agegrp = "A00",
      industry = "00",
      key = my_key
    )
  
  resp <- tryCatch(
    req |> req_perform(),
    error = function(e) return(NULL)
  )
  
  if (is.null(resp)) {
    return(tibble())
  }
  
  txt <- tryCatch(
    resp_body_string(resp),
    error = function(e) return("")
  )
  
  if (nchar(txt) == 0 || grepl("<html", txt)) {
    return(tibble())
  }
  
  parsed <- tryCatch(
    jsonlite::fromJSON(txt),
    error = function(e) return(NULL)
  )
  
  if (is.null(parsed) || length(parsed) < 2) {
    return(tibble())
  }
  
  df <- as_tibble(parsed[-1, , drop = FALSE])
  names(df) <- parsed[1, ]
  
  df %>%
    mutate(
      state = sprintf("%02d", as.integer(state)),
      county = sprintf("%03d", as.integer(county)),
      county_fips = paste0(state, county)
    )
  
}

#Function to pull all counties and quarters for a single variable
pull_all_qwi <- function(variable) {
  
  grid <- expand.grid(
    state = sprintf("%02d", 1:56),
    time = sprintf(
      "%d-Q%d",
      rep(2006:2025, each = 4),
      1:4
    ),
    stringsAsFactors = FALSE
  )
  
  results <- vector("list", nrow(grid))
  
  for (i in seq_len(nrow(grid))) {
    
    if (i %% 100 == 0) {
      message(i, " of ", nrow(grid), " requests completed")
    }
    
    results[[i]] <- tryCatch(
      get_qwi_county(
        state_fips = grid$state[i],
        time_period = grid$time[i],
        variable = variable
      ),
      error = function(e) tibble()
    )
    
  }
  
  bind_rows(results)
  
}

#Real Pulls of Employment Variables
turnover <- pull_all_qwi("TurnOvrS")
employment <- pull_all_qwi("Emp")
earnings <- pull_all_qwi("EarnS")
separations <- pull_all_qwi("Sep")
job_creation <- pull_all_qwi("FrmJbC")
hires <- pull_all_qwi("HirA")
job_losses <- pull_all_qwi("FrmJbLs")


#Saving Each Pull as a Dataset
saveRDS(turnover, "qwi_turnover.rds")
saveRDS(employment, "qwi_employment.rds")
saveRDS(earnings, "qwi_earnings.rds")
saveRDS(separations, "qwi_separations.rds")
saveRDS(job_creation, "qwi_job_creation.rds")
saveRDS(hires, "qwi_hires.rds")
saveRDS(job_losses, "qwi_job_losses.rds")


#Merge Into a Single Panel Dataset
qwi_panel <- turnover %>%
  left_join(
    employment %>%
      select(county_fips, time, Emp),
    by = c("county_fips", "time")
  ) %>%
  left_join(
    earnings %>%
      select(county_fips, time, EarnS),
    by = c("county_fips", "time")
  ) %>%
  left_join(
    separations %>%
      select(county_fips, time, Sep),
    by = c("county_fips", "time")
  ) %>%
  left_join(
    job_creation %>%
      select(county_fips, time, FrmJbC),
    by = c("county_fips", "time")
  ) %>%
  left_join(
    hires %>%
      select(county_fips, time, HirA),
    by = c("county_fips", "time")
  ) %>%
  left_join(
    job_losses %>%
      select(county_fips, time, FrmJbLs),
    by = c("county_fips", "time")
  )

#Add County Names to Panel
county_lookup <- fips_codes %>%
  distinct(
    state_code,
    county_code,
    county,
    state
  ) %>%
  mutate(
    county_fips = paste0(state_code, county_code)
  ) %>%
  rename(
    county_name = county,
    state_name = state
  ) %>%
  select(
    county_fips,
    county_name,
    state_name
  )

qwi_panel <- qwi_panel %>%
  left_join(
    county_lookup,
    by = "county_fips"
  )



#Create Rolling Averages for Churn Data

qwi_panel <- qwi_panel %>%
  mutate(
    year = as.integer(substr(time, 1, 4)),
    quarter = as.integer(substr(time, 7, 7)),
    quarter_index = year * 4 + quarter
  ) %>%
  arrange(county_fips, quarter_index)


qwi_panel <- qwi_panel %>%
  mutate(
    HirA = as.numeric(HirA),
    Sep = as.numeric(Sep),
    churn_raw = HirA + Sep
  )

qwi_panel <- qwi_panel %>%
  arrange(county_fips, time) %>%
  group_by(county_fips) %>%
  mutate(
    churn_4q = slide_dbl(
      churn_raw,
      mean,
      .before = 3,
      .complete = TRUE,
      .na_rm = TRUE
    )
  ) %>%
  ungroup()


qwi_panel <- qwi_panel %>%
  mutate(
    TurnOvrS = as.numeric(TurnOvrS)
  ) %>%
  arrange(county_fips, time) %>%
  group_by(county_fips) %>%
  mutate(
    turnover_churn = slide_dbl(
      TurnOvrS,
      mean,
      .before = 3,
      .complete = TRUE,
      .na_rm = TRUE
    )
  ) %>%
  ungroup()

write_csv(qwi_panel, here("01_tidydata", "QuarterlyWorkforceIndicators0625.csv"))
```

```{r Step 3: Append CES Survey Data, include=TRUE}
ces06_clean <- ces06 %>%
  transmute(
    year = 2006,
    weight = v1001,
    case_id = v1000,
    state_fips = NA,
    county_fips = v1004,
    reg_status = v3004,
    national_economy_raw = v3008,
    personal_finance_raw = NA,
    state_of_us_economy = v2135,
    state_of_local_economy = v2136,
    political_interest_raw = v2042,
    pres_approval = v3003,
    house_approval = v3017,
    party_id_7 = v3007,
    ideology = v2021,
    homeowner = v2033,
    income = v2032, 
    race = v2005,
    gender = v2004,
    education = v2018,
    emp_status = v2030,
    age_cat = NA,
    birth_year = v2020,
    marital_status = v2019,
  )


ces07_clean <- ces07 %>%
   transmute(
    year = 2007,
    case_id = caseid,
    weight = weight,
    state_fips = NA,
    county_fips = CC06_V1004,
    reg_status = CC06_V3004,
    national_economy_raw = CC06_V3008,
    personal_finance_raw = NA,
    state_of_us_economy = CC06_V2135, 
    state_of_local_economy = CC06_V2136,
    political_interest_raw = polinterest,
    pres_approval = CC06_V3003,
    house_approval = CC06_V3017,
    party_id_7 = pid7,
    ideology = CC06_V2021,
    homeowner = CC06_V2033,
    income = CC06_V2032, 
    race = CC06_V2005,
    gender = CC06_V2004,
    education = CC06_V2018,
    emp_status = CC06_V2030,
    age_cat = NA,
    birth_year = CC06_V2020, 
    marital_status = CC06_V2019,
  )

ces08_clean <- ces08 %>%
    transmute(
    year = 2008,
    case_id = V100,
    weight = V201,
    state_fips = V251,
    county_fips = V269,
    reg_status = V203,
    national_economy_raw = CC302,
    personal_finance_raw = CC304c,
    pres_approval = CC335bush,
    house_approval = CC335rep,
    state_of_us_economy = NA, 
    state_of_local_economy = NA,
    political_interest_raw = V244,
    party_id_7 = CC424,
    ideology = V243,
    homeowner = CC333,
    income = V246, 
    race = V211,
    gender = V208,
    education = V213,
    emp_status = V209,
    age_cat = NA,
    birth_year = V207, 
    marital_status = V214,
  )


ces09_clean <- ces09 %>%
    transmute(
    year = 2009,
    case_id = v100,
    weight = v200,
    state_fips = v265,
    county_fips = v269,
    reg_status = v256,
    national_economy_raw = cc09_20,
    personal_finance_raw = cc09_21b3,
    pres_approval = cc09_43e,
    house_approval = cc09_43a,
    state_of_us_economy = NA, 
    state_of_local_economy = NA,
    political_interest_raw = v244,
    party_id_7 = cc424,
    ideology = v261,
    homeowner = cc09_05,
    income = v246, 
    race = v211,
    gender = v208,
    education = v213,
    emp_status = v209,
    age_cat = v247,
    birth_year = NA,
    age = v288,
    marital_status = v214,
  )

ces10_clean <- ces10 %>%
    transmute(
    year = 2010,
    case_id = V100,
    weight = V101,
    state_fips = V302_post,
    county_fips = V277_post,
    reg_status = V203_post,
    national_economy_raw = CC302,
    personal_finance_raw = NA,
    pres_approval = CC308a,
    house_approval = CC315a,
    state_of_us_economy = NA, 
    state_of_local_economy = NA,
    political_interest_raw = V244,
    party_id_7 = V212d,
    ideology = V243,
    homeowner = V250,
    income = V246, 
    race = V211,
    gender = V208,
    education = V213,
    emp_status = V209,
    age_cat = NA,
    birth_year = V207,
    age = NA,
    marital_status = V214,
  )

ces11_clean <- ces11 %>%
    transmute(
    year = 2011,
    case_id = V100,
    weight = V101,
    state_fips = V302,
    county_fips = V303,
    reg_status = V203,
    national_economy_raw = CC310,
    personal_finance_raw = NA,
    pres_approval = CC320a,
    house_approval = CC323a,
    state_of_us_economy = NA, 
    state_of_local_economy = NA,
    political_interest_raw = V244,
    party_id_7 = V212d,
    ideology = V243,
    homeowner = CC306,
    income = V246, 
    race = V211,
    gender = V208,
    education = V213,
    emp_status = V209,
    age_cat = NA,
    birth_year = V207,
    age = NA,
    marital_status = V214,
  )

ces12_clean <- ces12 %>%
    transmute(
    year = 2012,
    case_id = V101,
    weight = V103,
    state_fips = NA,
    county_fips = countyfips,
    reg_status = votereg,
    national_economy_raw = CC302,
    personal_finance_raw = CC304,
    pres_approval = CC308a,
    house_approval = CC315a,
    state_of_us_economy = NA, 
    state_of_local_economy = NA,
    political_interest_raw = newsint,
    party_id_7 = pid7,
    ideology = ideo5,
    homeowner = ownhome,
    income = faminc, 
    race = race,
    gender = gender,
    education = educ,
    emp_status = employ,
    age_cat = NA,
    birth_year = birthyr,
    age = NA,
    marital_status = marstat,
  )

ces13_clean <- ces13 %>%
    transmute(
    year = 2013,
    case_id = caseid,
    weight = weight,
    state_fips = NA,
    county_fips = countyfips,
    reg_status = votereg,
    national_economy_raw = CC13_302,
    personal_finance_raw = CC305,
    pres_approval = CC312a,
    house_approval = CC13_313a,
    state_of_us_economy = NA, 
    state_of_local_economy = NA,
    political_interest_raw = newsint,
    party_id_7 = pid7,
    ideology = ideo5,
    homeowner = ownhome,
    income = faminc, 
    race = race,
    gender = gender,
    education = educ,
    emp_status = employ,
    age_cat = NA,
    birth_year = birthyr,
    age = NA,
    marital_status = marstat,
  )

ces14_clean <- ces14 %>%
    transmute(
    year = 2014,
    case_id = V101,
    weight = weight,
    state_fips = NA,
    county_fips = countyfips,
    reg_status = votereg,
    national_economy_raw = CC14_302,
    personal_finance_raw = CC14_304,
    pres_approval = CC14_308a,
    house_approval = CC14_315a,
    state_of_us_economy = NA, 
    state_of_local_economy = NA,
    political_interest_raw = newsint,
    party_id_7 = pid7,
    ideology = ideo5,
    homeowner = ownhome,
    income = faminc, 
    race = race,
    gender = gender,
    education = educ,
    emp_status = employ,
    age_cat = NA,
    birth_year = birthyr,
    age = NA,
    marital_status = marstat,
  )

ces15_clean <- ces15 %>%
    transmute(
    year = 2015,
    case_id = V101,
    weight = weight,
    state_fips = NA,
    county_fips = countyfips,
    reg_status = votereg,
    national_economy_raw = CC15_302,
    personal_finance_raw = NA,
    pres_approval = CC15_312a,
    house_approval = CC15_313a,
    state_of_us_economy = NA, 
    state_of_local_economy = NA,
    political_interest_raw = newsint,
    party_id_7 = pid7,
    ideology = ideo5,
    homeowner = ownhome,
    income = faminc, 
    race = race,
    gender = gender,
    education = educ,
    emp_status = employ,
    age_cat = NA,
    birth_year = birthyr,
    age = NA,
    marital_status = marstat,
  )

ces16_clean <- ces16 %>%
    transmute(
    year = 2015,
    case_id = V101,
    weight = commonweight_vv,
    state_fips = NA,
    county_fips = countyfips,
    reg_status = votereg,
    national_economy_raw = CC16_302,
    personal_finance_raw = CC16_303,
    pres_approval = CC16_320a,
    house_approval = CC16_320f,
    state_of_us_economy = NA, 
    state_of_local_economy = NA,
    political_interest_raw = newsint,
    party_id_7 = pid7,
    ideology = ideo5,
    homeowner = ownhome,
    income = faminc, 
    race = race,
    gender = gender,
    education = educ,
    emp_status = employ,
    age_cat = NA,
    birth_year = birthyr,
    age = NA,
    marital_status = marstat,
  )


ces17_full <- ces17 %>%
  left_join(
    ces17_county_addition,
    by = "V101"
  )

ces17_clean <- ces17_full %>%
    transmute(
    year = 2017,
    case_id = V101,
    weight = weights_common,
    state_fips = NA,
    county_fips = countyfips,
    reg_status = votereg,
    national_economy_raw = CC17_301,
    personal_finance_raw = CC17_302,
    pres_approval = CC17_322a,
    house_approval = CC17_323a,
    state_of_us_economy = NA, 
    state_of_local_economy = NA,
    political_interest_raw = newsint,
    party_id_7 = pid7,
    ideology = ideo5,
    homeowner = ownhome,
    income = faminc_new, 
    race = race,
    gender = gender,
    education = educ,
    emp_status = employ,
    age_cat = NA,
    birth_year = birthyr,
    age = NA,
    marital_status = marstat,
  )

ces18_clean <- ces18 %>%
    transmute(
    year = 2018,
    case_id = caseid,
    weight = commonweight,
    state_fips = NA,
    county_fips = countyfips,
    reg_status = votereg,
    national_economy_raw = CC18_301,
    personal_finance_raw = CC18_302,
    pres_approval = CC18_308a,
    house_approval = CC18_311a,
    state_of_us_economy = NA, 
    state_of_local_economy = NA,
    political_interest_raw = newsint,
    party_id_7 = pid7,
    ideology = ideo5,
    homeowner = ownhome,
    income = faminc_new, 
    race = race,
    gender = gender,
    education = educ,
    emp_status = employ,
    age_cat = NA,
    birth_year = birthyr,
    age = NA,
    marital_status = marstat,
  )

ces19_clean <- ces19 %>%
    transmute(
    year = 2019,
    case_id = caseid,
    weight = commonweight,
    state_fips = NA,
    county_fips = countyfips,
    reg_status = votereg,
    national_economy_raw = CC19_301,
    personal_finance_raw = CC19_302,
    pres_approval = CC19_308a,
    house_approval = CC19_311a,
    state_of_us_economy = NA, 
    state_of_local_economy = NA,
    political_interest_raw = newsint,
    party_id_7 = pid7,
    ideology = ideo5,
    homeowner = ownhome,
    income = faminc_new, 
    race = race,
    gender = gender,
    education = educ,
    emp_status = employ,
    age_cat = NA,
    birth_year = birthyr,
    age = NA,
    marital_status = marstat,
  )

ces20_clean <- ces20 %>%
    transmute(
    year = 2020,
    case_id = caseid,
    weight = commonweight,
    state_fips = NA,
    county_fips = countyfips,
    reg_status = votereg,
    national_economy_raw = CC20_302,
    personal_finance_raw = CC20_303,
    pres_approval = CC20_320a,
    house_approval = CC20_320f,
    state_of_us_economy = NA, 
    state_of_local_economy = NA,
    political_interest_raw = newsint,
    party_id_7 = pid7,
    ideology = ideo5,
    homeowner = ownhome,
    income = faminc_new, 
    race = race,
    gender = gender,
    education = educ,
    emp_status = employ,
    age_cat = NA,
    birth_year = birthyr,
    age = NA,
    marital_status = marstat,
  )

ces21_clean <- ces21 %>%
    transmute(
    year = 2021,
    case_id = caseid,
    weight = commonweight,
    state_fips = NA,
    county_fips = countyfips,
    reg_status = votereg,
    national_economy_raw = CC21_301,
    personal_finance_raw = CC21_302,
    pres_approval = CC21_315a,
    house_approval = CC21_315f,
    state_of_us_economy = NA, 
    state_of_local_economy = NA,
    political_interest_raw = newsint,
    party_id_7 = pid7,
    ideology = ideo5,
    homeowner = ownhome,
    income = faminc_new, 
    race = race,
    gender = gender4,
    education = educ,
    emp_status = employ,
    age_cat = NA,
    birth_year = birthyr,
    age = NA,
    marital_status = marstat,
  )


ces22_clean <- ces22 %>%
    transmute(
    year = 2022,
    case_id = caseid,
    weight = commonweight,
    state_fips = NA,
    county_fips = countyfips,
    reg_status = votereg,
    national_economy_raw = CC22_302,
    personal_finance_raw = CC22_303,
    pres_approval = CC22_320a,
    house_approval = CC22_320f,
    state_of_us_economy = NA, 
    state_of_local_economy = NA,
    political_interest_raw = newsint,
    party_id_7 = pid7,
    ideology = ideo5,
    homeowner = ownhome,
    income = faminc_new, 
    race = race,
    gender = gender4,
    education = educ,
    emp_status = employ,
    age_cat = NA,
    birth_year = birthyr,
    age = NA,
    marital_status = marstat,
  )

ces23_clean <- ces23 %>%
    transmute(
    year = 2023,
    case_id = caseid,
    weight = commonweight,
    state_fips = NA,
    county_fips = countyfips,
    reg_status = votereg,
    national_economy_raw = CC23_301,
    personal_finance_raw = CC23_302,
    pres_approval = CC23_312a,
    house_approval = CC23_312f,
    state_of_us_economy = NA, 
    state_of_local_economy = NA,
    political_interest_raw = newsint,
    party_id_7 = pid7,
    ideology = ideo5,
    homeowner = ownhome,
    income = faminc_new, 
    race = race,
    gender = gender4,
    education = educ,
    emp_status = employ,
    age_cat = NA,
    birth_year = birthyr,
    age = NA,
    marital_status = marstat,
  )

ces24_clean <- ces24 %>%
    transmute(
    year = 2024,
    case_id = caseid,
    weight = commonweight,
    state_fips = NA,
    county_fips = countyfips,
    reg_status = votereg,
    national_economy_raw = CC24_301,
    personal_finance_raw = CC24_302,
    pres_approval = CC24_312a,
    house_approval = CC24_312f,
    state_of_us_economy = NA, 
    state_of_local_economy = NA,
    political_interest_raw = newsint,
    party_id_7 = pid7,
    ideology = ideo5,
    homeowner = ownhome,
    income = faminc_new, 
    race = race,
    gender = gender4,
    education = educ,
    emp_status = employ,
    age_cat = NA,
    birth_year = birthyr,
    age = NA,
    marital_status = marstat,
  )

ces25_clean <- ces25 %>%
    transmute(
    year = 2025,
    case_id = caseid,
    weight = commonweight,
    state_fips = NA,
    county_fips = countyfips,
    reg_status = votereg,
    national_economy_raw = CC25_301,
    personal_finance_raw = CC25_302,
    pres_approval = CC25_312a,
    house_approval = CC25_312f,
    state_of_us_economy = NA, 
    state_of_local_economy = NA,
    political_interest_raw = newsint,
    party_id_7 = pid7,
    ideology = ideo5,
    homeowner = ownhome,
    income = faminc_new, 
    race = race,
    gender = gender4,
    education = educ,
    emp_status = employ,
    age_cat = NA,
    birth_year = birthyr,
    age = NA,
    marital_status = marstat,
  )


ceslist <- list(
  ces06_clean,
  ces07_clean,
  ces08_clean,
  ces09_clean,
  ces10_clean,
  ces11_clean,
  ces12_clean,
  ces13_clean,
  ces14_clean,
  ces15_clean,
  ces16_clean,
  ces17_clean,
  ces18_clean,
  ces19_clean,
  ces20_clean,
  ces21_clean,
  ces22_clean,
  ces23_clean,
  ces24_clean,
  ces25_clean
)


#Clean Up County FIPS codes
ces06_clean <- ces06_clean %>%
  mutate(
    county_fips = str_pad(
      as.character(county_fips),
      width = 5,
      side = "left",
      pad = "0"
    )
  )

ces07_clean <- ces07_clean %>%
  mutate(
    county_fips = str_pad(
      as.character(county_fips),
      width = 5,
      side = "left",
      pad = "0"
    )
  )  

ces08_clean <- ces08_clean %>%
  mutate(
    state_fips = str_pad(
      as.character(state_fips),
      width = 2,
      side = "left",
      pad = "0"
    ),

    county_fips = str_pad(
      as.character(county_fips),
      width = 3,
      side = "left",
      pad = "0"
    ),

    county_fips = paste0(state_fips, county_fips)
  )

ces09_clean <- ces09_clean %>%
  mutate(
    state_fips = str_pad(
      as.character(state_fips),
      width = 2,
      side = "left",
      pad = "0"
    ),

    county_fips = str_pad(
      as.character(county_fips),
      width = 3,
      side = "left",
      pad = "0"
    ),

    county_fips = paste0(state_fips, county_fips)
  )

ces11_clean <- ces11_clean %>%
  mutate(
    state_fips = str_pad(
      as.character(state_fips),
      width = 2,
      side = "left",
      pad = "0"
    ),

    county_fips = str_pad(
      as.character(county_fips),
      width = 3,
      side = "left",
      pad = "0"
    ),

    county_fips = paste0(state_fips, county_fips)
  )

ces24_clean <- ces24_clean %>%
  mutate(
    county_fips = str_pad(
      as.character(county_fips),
      width = 5,
      side = "left",
      pad = "0"
    )
  )

ces25_clean <- ces25_clean %>%
  mutate(
    county_fips = str_pad(
      as.character(county_fips),
      width = 5,
      side = "left",
      pad = "0"
    )
  )

#Bind Rows
cespanel <- bind_rows(
  ces06_clean,
  ces07_clean,
  ces08_clean,
  ces09_clean,
  ces10_clean,
  ces11_clean,
  ces12_clean,
  ces13_clean,
  ces14_clean,
  ces15_clean,
  ces16_clean,
  ces17_clean,
  ces18_clean,
  ces19_clean,
  ces20_clean,
  ces21_clean,
  ces22_clean,
  ces23_clean,
  ces24_clean,
  ces25_clean
)

```

```{r Step 4: Merging CES Data to QWI and Tausanovitch and Warshaw Data, include=TRUE}
#Cleaning and Merging Workforce Data 
qwi_panel <- qwi_panel %>%
  mutate(
    year = as.integer(substr(time, 1, 4))
  )

qwi_yearly <- qwi_panel %>%
  group_by(county_fips, year) %>%
  summarize(
    churn_4q = mean(churn_4q, na.rm = TRUE),
    churn_raw = mean(churn_raw, na.rm = TRUE),

    TurnOvrS = mean(TurnOvrS, na.rm = TRUE),
    Emp = mean(Emp, na.rm = TRUE),
    EarnS = mean(EarnS, na.rm = TRUE),
    Sep = mean(Sep, na.rm = TRUE),
    FrmJbC = mean(FrmJbC, na.rm = TRUE),
    FrmJbLs = mean(FrmJbLs, na.rm = TRUE),
    HirA = mean(HirA, na.rm = TRUE),

    .groups = "drop"
  )

qwi_yearly %>%
  count(year)

analysis_data <- cespanel %>%
  left_join(
    qwi_yearly,
    by = c( "county_fips", "year"
    )
  )


#Tausanovitch and Warshaw Data 
county_ideology_1 <- county_ideology_1 %>%
  mutate(
    county_fips = str_pad(
      as.character(county_fips),
      width = 5,
      side = "left",
      pad = "0"
    )
  )

county_ideology_1 <- county_ideology_1 %>%
  mutate(
    start_year = as.integer(str_extract(survey_period, "^\\d{4}")),
    end_year = as.integer(str_extract(survey_period, "\\d{4}$"))
  )

county_ideology_yearly <- county_ideology_1 %>%
  mutate(
    start_year = as.integer(str_extract(survey_period, "^\\d{4}")),
    end_year = as.integer(str_extract(survey_period, "\\d{4}$"))
  ) %>%
  rowwise() %>%
  mutate(year = list(start_year:end_year)) %>%
  unnest(year) %>%
  ungroup()

analysis_data <- analysis_data %>%
  left_join(
    county_ideology_yearly,
    by = c( "county_fips", "year")
  )


``` 

```{r Step 5, Merge Data to County Level Census Characteristics, include=TRUE}
census_api_key("1a447b57b802a82f3c8a2a62cd499bb781c2fbc6", install = FALSE)

v12 <- load_variables(2012, "acs5", cache = TRUE)


#Variable Definition
acs_vars <- c(

  # Population
  population = "B01003_001",

  # Income
  med_income = "B19013_001",

  # Inequality
  gini = "B19083_001",

  # Poverty
  poverty_total = "B17001_001",
  poverty_under = "B17001_002",

  # Employment
  labor_force = "B23025_003",
  unemployed = "B23025_005",

  # Education
  education_total = "B15003_001",
  bachelors = "B15003_022",
  masters = "B15003_023",
  executive_ed = "B15003_024",
  doctorate = "B15003_025",

  # Race/Ethnicity
  white_nonhisp = "B03002_003",
  black_nonhisp = "B03002_004",
  asian_nonhisp = "B03002_006",
  hispanic = "B03002_012",

  # Housing
  median_rent = "B25064_001",
  median_home_value = "B25077_001",

  owner_occ = "B25003_002",
  renter_occ = "B25003_003",

  # Rent burden
  rent_total = "B25070_001",
  rent_burdened_30_34 = "B25070_007",
  rent_burdened_35_39 = "B25070_008",
  rent_burdened_40_49 = "B25070_009",
  rent_burdened_50_up = "B25070_010",

  # Vacancy
  housing_units = "B25002_001",
  occupied_units = "B25002_002",

  # Household size
  avg_household_size = "B25010_001",
  
  #Industry Classifications
  agriculture      = "C24050_002",
  construction     = "C24050_003",
  manufacturing    = "C24050_004",
  wholesale_trade  = "C24050_005",
  retail_trade     = "C24050_006",
  transportation   = "C24050_007",
  information      = "C24050_008",
  finance          = "C24050_009",
  professional     = "C24050_010",
  education_health = "C24050_011",
  arts             = "C24050_012",
  other_services   = "C24050_013",
  public_admin     = "C24050_014"
)

years <- 2012:2024

acs_list <- lapply(years, function(yr) {

  message("Pulling ACS ", yr)

  get_acs(
    geography = "county",
    year = yr,
    survey = "acs5",
    variables = acs_vars,
    output = "wide"
  ) %>%
    mutate(year = yr)

})

acs_raw <- bind_rows(acs_list)
#write_csv(acs_raw, here("01_tidydata", "Census_County_Data_1225.csv"))
#acs_raw <- read_csv(here("01_tidydata", "Census_County_Data_1225.csv"))


#Create Calculated Measures for County-Level Characteristics
county_covars_acs <- acs_raw %>%
  transmute(

    county_fips = GEOID,
    county_name = NAME,
    year,

    population = populationE,
    log_population = log(populationE),

    med_income = med_incomeE,
    gini = giniE,

    poverty_rate =
      100 * poverty_underE / poverty_totalE,

    unemployment_rate =
      100 * unemployedE / labor_forceE,

    pct_bachelors_plus =
      100 * (
        bachelorsE +
        mastersE +
        professionalE +
        doctorateE
      ) / education_totalE,

    pct_white =
      100 * white_nonhispE / populationE,

    pct_black =
      100 * black_nonhispE / populationE,

    pct_asian =
      100 * asian_nonhispE / populationE,

    pct_hispanic =
      100 * hispanicE / populationE,

    homeownership_rate =
      100 * owner_occE /
      (owner_occE + renter_occE),

    pct_cost_burdened =
      100 * (rent_burdened_30_34E + rent_burdened_35_39E + rent_burdened_40_49E + rent_burdened_50_upE) /
      rent_totalE,

    housing_vacancy_rate =
      100 * (housing_unitsE - occupied_unitsE) /
      housing_unitsE,

    avg_household_size =
      avg_household_sizeE,

    median_rent = median_rentE,

    median_home_value =
      median_home_valueE,
    
    industry_total =
      agricultureE +
      constructionE +
      manufacturingE +
      wholesale_tradeE +
      retail_tradeE +
      transportationE +
      informationE +
      financeE +
      professionalE +
      education_healthE +
      artsE +
      other_servicesE +
      public_adminE,

    agriculture_share =
      agricultureE / industry_total,

    construction_share =
      constructionE / industry_total,

    manufacturing_share =
      manufacturingE / industry_total,

    wholesale_trade_share =
      wholesale_tradeE / industry_total,

    retail_trade_share =
      retail_tradeE / industry_total,

    transportation_share =
      transportationE / industry_total,

    information_share =
      informationE / industry_total,

    finance_share =
      financeE / industry_total,

    professional_share =
      professionalE / industry_total,

    education_health_share =
      education_healthE / industry_total,

    arts_share =
      artsE / industry_total,

    other_services_share =
      other_servicesE / industry_total,

    public_admin_share =
      public_adminE / industry_total,

    industry_hhi =
      agriculture_share^2 +
      construction_share^2 +
      manufacturing_share^2 +
      wholesale_trade_share^2 +
      retail_trade_share^2 +
      transportation_share^2 +
      information_share^2 +
      finance_share^2 +
      professional_share^2 +
      education_health_share^2 +
      arts_share^2 +
      other_services_share^2 +
      public_admin_share^2,

    industry_diversity =
      1 - industry_hhi
  )


#Get ACS Census Data for 2006-2012 Covariates

acs_vars_pre <- c(
  # Population
  population = "B00001_001",

  # Income
  med_income = "B06011PR_001",

  # Inequality
  gini = "B19083_001",

  # Poverty
  poverty_total = "B06012_001",
  poverty_under = "B06012_002",

  # Employment
  labor_force = "B10058_002",
  unemployed = "B21005_011",
  unemployed_vet = "B21005_017",

  # Education (All are the same for post-Bachelors) 
  education_total = "B06009_001",
  bachelors = "B06009_005",
  post_bach = "B06009_006",

  # Race/Ethnicity
  white_nonhisp = "B02001_002",
  black_nonhisp = "B02001_003",
  asian_nonhisp = "B02001_005",
  hispanic = "B03002_012",

  # Housing
  median_rent = "B25113_001",
  median_home_value = "B25107_001",

  owner_occ = "B10061_002",
  renter_occ = "B25003_003",

  # Rent burden
  rent_total = "B25070_001",
  rent_burdened_30_34 = "B25070_007",
  rent_burdened_35_39 = "B25070_008",
  rent_burdened_40_49 = "B25070_009",
  rent_burdened_50_up = "B25070_010",


  # Vacancy
  housing_units = "B25004_001",
  vacant_units = "B25002_003",

  # Household size
  avg_household_size = "B25010_001",
  
  #Industry Classifications
  agriculture      = "C24050_002",
  construction     = "C24050_003",
  manufacturing    = "C24050_004",
  wholesale_trade  = "C24050_005",
  retail_trade     = "C24050_006",
  transportation   = "C24050_007",
  information      = "C24050_008",
  finance          = "C24050_009",
  professional     = "C24050_010",
  education_health = "C24050_011",
  arts             = "C24050_012",
  other_services   = "C24050_013",
  public_admin     = "C24050_014"
  
  
)


v10 <- load_variables(2010, "acs5")

years_pre <- 2010:2011

acs_list_pre <- lapply(years_pre, function(yr) {

  message("Pulling ACS ", yr)

  get_acs(
    geography = "county",
    year = yr,
    survey = "acs5",
    variables = acs_vars_pre,
    output = "wide"
  ) %>%
    mutate(year = yr)

})

acs_pre_raw <- bind_rows(acs_list_pre) 

county_covars_pre <- acs_pre_raw %>%
  transmute(
    county_fips = GEOID,
    county_name = NAME,
    year,

    population = populationE,
    log_population = log(populationE),

    med_income = med_incomeE,
    gini = giniE,

    poverty_rate =
      100 * poverty_underE / poverty_totalE,

    unemployment_rate =
      100 * unemployedE / labor_forceE,

    pct_bachelors_plus =
      100 * (
        bachelorsE +
        post_bachE
      ) / education_totalE,

    pct_white =
      100 * white_nonhispE / populationE,

    pct_black =
      100 * black_nonhispE / populationE,

    pct_asian =
      100 * asian_nonhispE / populationE,

    pct_hispanic =
      100 * hispanicE / populationE,

    homeownership_rate =
      100 * owner_occE /
      (owner_occE + renter_occE),

    pct_cost_burdened =
      100 * (rent_burdened_30_34E + rent_burdened_35_39E + rent_burdened_40_49E + rent_burdened_50_upE) /
      rent_totalE,

    housing_vacancy_rate =
      100 * (vacant_unitsE) /
      housing_unitsE,

    avg_household_size =
      avg_household_sizeE,

    median_rent = median_rentE,

    median_home_value =
      median_home_valueE,
    
    industry_total =
      agricultureE +
      constructionE +
      manufacturingE +
      wholesale_tradeE +
      retail_tradeE +
      transportationE +
      informationE +
      financeE +
      professionalE +
      education_healthE +
      artsE +
      other_servicesE +
      public_adminE,

    agriculture_share =
      agricultureE / industry_total,

    construction_share =
      constructionE / industry_total,

    manufacturing_share =
      manufacturingE / industry_total,

    wholesale_trade_share =
      wholesale_tradeE / industry_total,

    retail_trade_share =
      retail_tradeE / industry_total,

    transportation_share =
      transportationE / industry_total,

    information_share =
      informationE / industry_total,

    finance_share =
      financeE / industry_total,

    professional_share =
      professionalE / industry_total,

    education_health_share =
      education_healthE / industry_total,

    arts_share =
      artsE / industry_total,

    other_services_share =
      other_servicesE / industry_total,

    public_admin_share =
      public_adminE / industry_total,

    industry_hhi =
      agriculture_share^2 +
      construction_share^2 +
      manufacturing_share^2 +
      wholesale_trade_share^2 +
      retail_trade_share^2 +
      transportation_share^2 +
      information_share^2 +
      finance_share^2 +
      professional_share^2 +
      education_health_share^2 +
      arts_share^2 +
      other_services_share^2 +
      public_admin_share^2,

    industry_diversity =
      1 - industry_hhi 
    )


county_covars_backfill <- county_covars_pre %>%
  filter(year == 2010) %>%
  select(-year) %>%
  tidyr::crossing(
    year = 2006:2009
  )

county_covars <- bind_rows(
  county_covars_backfill,
  county_covars_pre,
  county_covars_acł
)
```

```{r Step 6: Final Merge, include=TRUE}

#Final Merge
analysis_data <- analysis_data %>%
  left_join(
    county_covars,
    by = c("county_fips", "year")
  )
write_csv(analysis_data, here("01_tidydata", "CCESPanelData_Merged.csv"))
```