---
title: "merge_external_quality_measures"
output: html_document
---

```{r Step 0: Set-up, include=TRUE}
# ============================================================
# External Job Quality Measures + GSS Merge
# ============================================================
#
# Purpose:
#   Merge industry-year measures of objective job quality
#   to individual GSS respondents.
#
# External sources:
#   1. CPS ASEC adjusted industry wage premium
#   2. BLS ECEC benefits
#   3. BLS ECEC wages and salaries
#   4. BLS JOLTS employment stability
#   5. Census QWI earnings volatility
#
# ============================================================

library(tidyverse)
library(here)
library(gssr)
```


```{r Step 1: Data Ingestion, include=TRUE}
gss_all <- read_csv(here("01_tidydata", "GSS_Data_Cleaned", "gss_clean_2000_2024.csv"))
wage_premiums <- read_csv(here("01_tidydata", "IPUMS_CPS", "industry_wage_premium_2000_2025_n25.csv"))
ecec_benefits <- read_csv(here("01_tidydata", "BLS_ECEC", "ecec_benefits_industry_annual_2004_2024.csv"))
ecec_wages <- read_csv(here("01_tidydata", "BLS_ECEC", "ecec_wages_industry_annual_2004_2024.csv"))
jolts_turnover <- read_csv(here("01_tidydata", "BLS_JOLTS", "jolts_industry_annual_2000_2024.csv"))

```
